### ISSUE TITLE
Selected tab from overflow stays in overflow

### ISSUE THREAD

**Issue by paodb** [FlowingCode/EnhancedTabs#16]
### Describe the bug

Go to https://addonsv24.flowingcode.com/ and select Google Maps add-on from the side bar. See that Track Location demo is shown in the overflow. Click on it to see that demo. The demo is not shown adn the tab remains in the overflow. When repeating this steps but with the side bar being closed, then the tab seems to fit in the screen and the demo is then shown.

### Expected behavior

Tab should become visible when selected from overflow menu.

### Minimal reproducible example

![tabs-google-maps](https://github.com/FlowingCode/EnhancedTabs/assets/30666649/16f34100-5bb7-4a47-ba6c-12ccc77c793c)

### Add-on Version

1.1.0

### Vaadin Version

24.4.1

### Additional information

Tested on latest Chrome, zoom 100%. Resolution 1920 x 1080.

**Comment by javier-godoy** [comment]
@paodb Can you please try to reproduce again in staging? (I'm not sure if this is another occurrence of #17, or whether the long tab "clustering with custom renderer" requires additional processing when moving it out of the overflow section)

**Comment by paodb** [comment]
Still happening ![tabs-google-maps-issue-16](https://github.com/FlowingCode/EnhancedTabs/assets/30666649/70f93763-7eb0-4896-9426-2894cd9487af)

**Comment by javier-godoy** [comment]
#### Steps to reproduce 

Go to https://addonsv24-staging.flowingcode.com/googlemaps/

![image](https://github.com/FlowingCode/EnhancedTabs/assets/11554739/75a8c16c-f57d-4ec5-89a9-34ab9c371c48)

Select "Customized Marker Icons"

![image](https://github.com/FlowingCode/EnhancedTabs/assets/11554739/5232f8dc-5b1b-432f-ac40-d65cd0412a6b)

Expected behavior

![image](https://github.com/FlowingCode/EnhancedTabs/assets/11554739/86dd0071-3659-40e8-a354-ffdc71a28e86)
